//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int education_id { get; set; }
        public int id_user { get; set; }
        public string name { get; set; }
        public string InstitutionorOrganisation { get; set; }
        public string Year_of_passing { get; set; }
        public string education_aggregate { get; set; }
    
        public virtual user user { get; set; }
    }
}
