//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int post_id { get; set; }
        public int id_user { get; set; }
        public string post_date { get; set; }
        public string post_title { get; set; }
        public string post_descp { get; set; }
    
        public virtual user user { get; set; }
    }
}
